---
- include_vars: "{{ nodesfile }}"

- name: Copy private key into place
  template: src=hadoop_rsa dest=/home/{{ hadoop_user }}/.ssh/hadoop_rsa owner={{ hadoop_user }} group={{ hadoop_group}} mode=0600

- name: Copy slaves into place
  template: src=slaves dest=/usr/local/hadoop/etc/hadoop/slaves owner={{ hadoop_user }} group={{ hadoop_group}}

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa {{ item.hostname }}
  with_items: "{{ nodes }}"
  register: keyscans

- name: prepare known_hosts
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ item.stdout }}"
    regexp="^{{ item.item.hostname }}"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
  with_items: "{{ keyscans.results }}"

- name: prepare known_hosts entries
  shell: ssh-keyscan -t rsa 0.0.0.0
  register: keyscan_0_0_0_0

- name: add 0.0.0.0 to known_hosts for secondary namenode
  lineinfile: 
    dest=/home/{{ hadoop_user }}/.ssh/known_hosts
    create=yes
    state=present
    line="{{ keyscan_0_0_0_0.stdout }}"
    regexp="^0.0.0.0"
    owner={{ hadoop_user }}
    group={{ hadoop_group }}
